### ISSUE TITLE
Corrupted Staff

### ISSUE THREAD

**Issue by jonnyboy1242** [LlemonDuck/dps-calculator#69] opened 2022-06-27 23:58 UTC
Corrupted staff requires a 'spell' imput to calculate dps for gauntlet

**Comment by LlemonDuck** [comment] 2022-06-28 00:00
Duplicate of #67 fixed in #68 pending review on the plugin hub in runelite/plugin-hub#2884

**Closed by LlemonDuck** 2022-06-28 00:00 UTC
