### ISSUE TITLE
Ranged strength miscalculated / wrongly read

### ISSUE THREAD

**Issue by luuklelifeld** [LlemonDuck/dps-calculator#60] opened 2022-06-17 08:12 UTC
Since either the latest version (2.1.1) or the one before (2.1.0) ranged strength isn't being set correctly. It looks like the ranged accuracy value is also set to the ranged strength value, instead of actually getting the proper ranged strength value.

**Comment by LlemonDuck** [comment] 2022-06-17 15:40
Duplicate of #58 and already fixed. Your client should pick up the correct data next time it is restarted.

**Closed by LlemonDuck** 2022-06-17 15:40 UTC
