### ISSUE TITLE
Feature Request: Show enemy hit chance on you.

### ISSUE THREAD

**Issue by TalismanRS** [LlemonDuck/dps-calculator#39] opened 2022-02-24 08:22 UTC
Is it possible to add in the calculation for the enemies hit rate through your armor? Would be nice to help decide your personal balance between damage and sustain

**Comment by LlemonDuck** [comment] 2022-02-28 20:39
Semi-duplicate of #1. It would be a lot of re-organizational work on the current structure of the plugin to support two-way calculation, but it's doable.

Currently not a high priority, but if you'd like to follow that ticket, it'll be where I place updates if I take it on.

**Closed by LlemonDuck** 2022-02-28 20:39 UTC
