### ISSUE TITLE
Says max hit is 29 when it should be 13

### ISSUE THREAD

**Issue by MatthewFrisky** [LlemonDuck/dps-calculator#58] opened 2022-06-17 06:55 UTC
I have my setup with magic short bow(i) using broad arrows on a slayer task at 77 range and it says DPS is 6.499 and max hit is 29 but max hit should be 29 and DPS should be way less.

![image](https://user-images.githubusercontent.com/14241950/174242672-4a85bb1a-151d-49fc-b891-be214f01e7eb.png)
![image](https://user-images.githubusercontent.com/14241950/174242692-40d84dbe-947d-4f23-9508-266972cca460.png)
![image](https://user-images.githubusercontent.com/14241950/174242707-89356bb6-288b-4478-99d4-dc72fb2eed9c.png)
![image](https://user-images.githubusercontent.com/14241950/174242733-c08a7583-870a-4feb-b6dd-f4f0bde8bf2f.png)

**Comment by LlemonDuck** [comment] 2022-06-17 07:24
Looks like this was actually caused by a bug in the wiki scraper which was assigning ranged accuracy to ranged strength, rather than any bug in the formulas. Fixed in LlemonDuck/runelite-wiki-scraper@1d99caa11e2d9c05c4b994b9e2ef05c3c1def9b9.

This means I'll be able to fix the bug without making a new deploy to the plugin hub. The scraper has been re-run and the results were merged in from LlemonDuck/runelite-wiki-scraper#25. Your client should pick up the new item data next time it is restarted.

Here is the panel showing the correct DPS calculation (I will need to look into why the salve warning is appearing):

![image](https://user-images.githubusercontent.com/1868974/174247400-a426c5d4-ede8-41f5-9e7d-16968c0eed1e.png)

**Closed by LlemonDuck** 2022-06-17 07:24 UTC

**Comment by LlemonDuck** [comment] 2022-06-17 07:40
Salve warning is now also fixed with more info here: 
* #59
