### ISSUE TITLE
Doesn't support Trident built-in Spells

### ISSUE THREAD

**Issue by TheL0rd0fSpace** [LlemonDuck/dps-calculator#72] opened 2022-07-02 17:42 UTC
When I set the plugin to use a Trident of the Swamp (e), it isn't able to calculate dps without me selecting a spell, even when I set the Attack Style to "Accurate" or "Longrange" rather than "Manual Cast". However, the in-built spell isn't an option on the spell list, so it's impossible to calculate dps with those items.

Further testing shows the same issue with Trident of the Swamp (not e), and Trident of the Seas.

![image](https://user-images.githubusercontent.com/26068263/177010868-b045c7b8-862d-454e-991f-d02d1f6f2dbe.png)

**Comment by LlemonDuck** [comment] 2022-07-03 03:48
Duplicate of #67 and #69

**Closed by LlemonDuck** 2022-07-03 03:48 UTC
